# Generated by Django 5.2 on 2025-04-25 10:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='api.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='BoardVessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ri', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ci', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rf', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cf', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('alive', models.BooleanField(default=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessels', to='api.board')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_vessels', to='api.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('col', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('result', models.IntegerField(choices=[(0, 'Water'), (1, 'Hit'), (2, 'Sunk')], default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='api.board')),
                ('board_vessel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shot', to='api.boardvessel')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='api.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='api.player')),
            ],
        ),
    ]
