# Generated by Django 5.2 on 2025-05-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vessel_board_boardvessel_shot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, related_name='games', to='api.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
