# Generated by Django 5.2 on 2025-05-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
