# Generated by Django 5.2 on 2025-05-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_game_players_alter_game_turn'),
        ('api', '0004_alter_game_turn'),
    ]

    operations = [
    ]
