# Generated by Django 5.2 on 2025-05-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20250525_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='games', to='api.player'),
        ),
    ]
